#!/usr/bin/env python

from setuptools import find_packages
from setuptools import setup
from subprocess import check_output
import os

name="master_exterior_ballistics"

# Fetch version from git tags, and write to version.py.
# When git is not available, use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), name, 'version.py')

try:
    v = check_output(["git", "describe"]).strip()
    sections = v.split('-', 3)
    version_git = sections.pop(0)
    if sections:
        incr = sections.pop(0)
        version_git += "." + incr
    git = ""
    if sections:
        git = sections.pop(0)
        version_git += "+" + git
except:
    with open(version_py, 'r') as fh:
        version_git = open(version_py).read().strip().split('=')[-1].replace('"','')

version_msg = "# Do not edit this file, versioning is governed by git tags"
with open(version_py, 'w') as fh:
    version_msg += os.linesep
    version_msg += "__version__=\"%s\"" % (version_git)
    version_msg += os.linesep
    fh.write(version_msg)

readme = open("README.md").read()

description = (
    "An exterior ballistics tool aimed at historical naval artillery."
)

setup(
    name="master_exterior_ballistics",
    version="{ver}".format(ver=version_git),
    description=description,
    long_description=readme,
    author="Simon Fowler",
    author_email="sjjfowler@gmail.com",
    url="https://github.com/sjjf/master_exterior_ballistics",
    license="GPLv3",
    packages=find_packages(),
    include_package_data=True,
    entry_points={
        'console_scripts': [
            'meb = master_exterior_ballistics.cli:main',
        ],
        'gui_scripts': [
            'meb-gui = master_exterior_ballistics.gui:main',
        ],
    },
    )
